# Generated by Django 5.0.14 on 2026-01-23 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan_code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='JANコード')),
                ('name', models.CharField(max_length=200, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='単価')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='商品画像URL')),
                ('alert_threshold', models.IntegerField(default=3, help_text='在庫がこの数を下回ったら通知', verbose_name='通知閾値')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='学生証番号(バーコード)')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('slack_user_id', models.CharField(blank=True, help_text='通知用。Uから始まるID', max_length=50, null=True, verbose_name='Slack Member ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', '購入'), ('RESTOCK', '入荷'), ('CORRECTION', '修正')], max_length=20, verbose_name='変動タイプ')),
                ('delta', models.IntegerField(help_text='購入ならマイナス、入荷ならプラスの値', verbose_name='変動数')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='store.product', verbose_name='商品')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.user', verbose_name='利用者')),
            ],
        ),
    ]
