# Generated by Django 5.0.14 on 2026-01-24 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slack_user_id',
        ),
    ]
