# Generated by Django 5.0.14 on 2026-02-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_user_slack_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransaction",
            name="amended_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="amendments",
                to="store.stocktransaction",
                verbose_name="修正対象",
            ),
        ),
    ]
